INSERT INTO categories (name_en, name_hi, slug, color, osm_tags, sort_order) VALUES
('Ration / Kirana', 'राशन / किराना', 'ration', '#9b7dff', '{"shop": "convenience"}', 1),
('Vegetables', 'सब्जी', 'vegetables', '#00dc64', '{"shop": "greengrocer"}', 2),
('Milk / Dairy', 'दूध / डेयरी', 'dairy', '#38bdf8', '{"shop": "dairy"}', 3),
('Medical / Pharmacy', 'दवाई', 'medical', '#fb7185', '{"amenity": "pharmacy"}', 4),
('Hardware', 'हार्डवेयर', 'hardware', '#fbbf24', '{"shop": "hardware"}', 5),
('Tailor', 'दर्जी', 'tailor', '#2dd4bf', '{"shop": "tailor"}', 6),
('Pet Shop', 'पेट शॉप', 'pet', '#fb923c', '{"shop": "pet"}', 7),
('Salon / Parlour', 'सैलून', 'salon', '#f472b6', '{"shop": "hairdresser"}', 8),
('Bakery', 'बेकरी', 'bakery', '#a78bfa', '{"shop": "bakery"}', 9),
('Tiffin / Dabba', 'टिफिन', 'tiffin', '#34d399', '{"amenity": "restaurant"}', 10),
('Laundry / Dhobi', 'धोबी', 'laundry', '#60a5fa', '{"shop": "laundry"}', 11),
('Stationery', 'स्टेशनरी', 'stationery', '#c084fc', '{"shop": "stationery"}', 12),
('LPG / Gas', 'गैस', 'lpg', '#f59e0b', '{"shop": "gas"}', 13),
('Mechanic', 'मैकेनिक', 'mechanic', '#6b7280', '{"shop": "car_repair"}', 14),
('Mobile Repair', 'मोबाइल रिपेयर', 'mobile-repair', '#3b82f6', '{"shop": "mobile_phone"}', 15),
('ATM / Bank', 'बैंक / ATM', 'bank', '#10b981', '{"amenity": "atm"}', 16),
('Auto / Rickshaw Stand', 'ऑटो स्टैंड', 'auto-stand', '#f97316', '{"amenity": "taxi"}', 17),
('Doctor / Clinic', 'डॉक्टर', 'clinic', '#ef4444', '{"amenity": "clinic"}', 18),
('Electrician', 'इलेक्ट्रीशियन', 'electrician', '#eab308', '{"craft": "electrician"}', 19),
('Plumber', 'प्लम्बर', 'plumber', '#0ea5e9', '{"craft": "plumber"}', 20);
